using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using SwiftMessageParser.Extensions;
using SwiftMessageParser.Entities.Tags.Pattern;
namespace SwiftMessageParser.Entities.Tags
{
    public class TagFactory
    {
        private Dictionary<string, Type> _mappings;
        private Dictionary<string, string> _swiftTagToITagMapping;

        public TagFactory()
        {
            LoadITagDataTypes();
            LoadTagToClassMappings();
        }
      
        public List<ITag> CreateInstance(string parsedSwiftTag, List<ITag> listOfITags)
        {
            Type itagToCreate = GetITagToCreateV2(parsedSwiftTag.Substring(1, 3).TrimColon());
            if (itagToCreate != null)
            {
                ITag instance = Activator.CreateInstance(itagToCreate) as ITag;
                instance.GetTagValues(parsedSwiftTag);
                listOfITags.Add(instance);
            }
            return listOfITags;
        }

        private Type GetITagToCreateV2(string iTagToCreate)
        {
            iTagToCreate = _swiftTagToITagMapping.Where(st => st.Key.Equals(iTagToCreate)).FirstOrDefault().Value;
            return string.IsNullOrEmpty(iTagToCreate) ? null : _mappings.Where(m => m.Key.Equals(iTagToCreate.ToUpper())).FirstOrDefault().Value;
        }

        //private Type GetITagToCreate(string iTagToInstatiate)
        //{
        //    foreach (KeyValuePair<string, string> keyValuePair in _swiftTagToITagMapping.OrderBy(tm => tm.Key))
        //    {
        //        if (keyValuePair.Key == iTagToInstatiate)
        //            iTagToInstatiate = _swiftTagToITagMapping[keyValuePair.Key];
        //    }
        //    foreach (KeyValuePair<string, Type> keyValuePair in _mappings.OrderBy(map => map.Key))
        //    {
        //        if (keyValuePair.Key.Contains(iTagToInstatiate.ToUpper()))
        //            return _mappings[keyValuePair.Key];
        //    }
        //    return null;
        //}

        private void LoadITagDataTypes()
        {
            _mappings = new Dictionary<string, Type>();
            foreach (Type type in Assembly.GetExecutingAssembly().GetTypes())
            {
                if (type.GetInterface(typeof(ITag).ToString()) != null)
                    _mappings.Add(type.Name.ToUpper(), type);
            }
        }

        private void LoadTagToClassMappings() => _swiftTagToITagMapping = new Dictionary<string, string>
            {
                { "11A", Patterns.DoubleSlashSeperator },
                { "12", Patterns.GetReference },
                { "12A", Patterns.OptionalCode },
                { "12B", Patterns.OptionalCode },
                { "12C", Patterns.DoubleSlashSeperator },
                { "12E", Patterns.GetReference },
                { "12F", Patterns.GetReference },
                { "13A", Patterns.DoubleSlashSeperator },
                { "13B", Patterns.OptionalCode },
                { "13E", Patterns.GetReference },
                { "13J", Patterns.DoubleSlashSeperator },
                { "13K", Patterns.DoubleSlashTypeQuantity },
                { "14", Patterns.GetReference },
                { "14C", Patterns.GetReference },
                { "14D", Patterns.GetReference },
                { "14F", Patterns.GetReference },
                { "14G", Patterns.SingleSlashSeperator },
                { "14J", Patterns.GetReference },
                { "14S", Patterns.GetReference },
                { "15A", Patterns.SequenceSeperator },
                { "15B", Patterns.SequenceSeperator },
                { "15C", Patterns.SequenceSeperator },
                { "15D", Patterns.SequenceSeperator },
                { "15E", Patterns.SequenceSeperator },
                { "15F", Patterns.SequenceSeperator },
                { "15G", Patterns.SequenceSeperator },
                { "15H", Patterns.SequenceSeperator },
                { "15I", Patterns.SequenceSeperator },
                { "15J", Patterns.SequenceSeperator },
                { "15K", Patterns.SequenceSeperator },
                { "15L", Patterns.SequenceSeperator },
                { "15M", Patterns.SequenceSeperator },
                { "15N", Patterns.SequenceSeperator },
                { "16A", Patterns.GetReference },
                { "16R", Patterns.GetReference },
                { "16S", Patterns.GetReference },
                { "17A", Patterns.GetReference },
                { "17B", Patterns.DoubleSlashSeperator },
                { "17F", Patterns.GetReference },
                { "17G", Patterns.GetReference },
                { "17N", Patterns.GetReference },
                { "17O", Patterns.GetReference },
                { "17R", Patterns.GetReference },
                { "17T", Patterns.GetReference },
                { "17U", Patterns.GetReference },
                { "17V", Patterns.GetReference },
                { "18A", Patterns.GetReference },
                { "19", Patterns.GetReference },
                { "19A", Patterns.SignCurrencyAmount },
                { "19B", Patterns.SignCurrencyAmount },
                { "20", Patterns.GetReference },
                { "20C", Patterns.DoubleSlashSeperator },
                { "20D", Patterns.DoubleSlashSeperator },
                { "21", Patterns.GetReference },
                { "21A", Patterns.GetReference },
                { "21B", Patterns.GetReference },
                { "21C", Patterns.GetReference },
                { "21D", Patterns.GetReference },
                { "21E", Patterns.GetReference },
                { "21F", Patterns.GetReference },
                { "21G", Patterns.GetReference },
                { "21N", Patterns.GetReference },
                { "21P", Patterns.GetReference },
                { "21R", Patterns.GetReference },
                { "22A", Patterns.GetReference },
                { "22B", Patterns.GetReference },
                { "22D", Patterns.GetReference },
                { "22E", Patterns.GetReference },
                { "22F", Patterns.OptionalCode },
                { "22G", Patterns.GetReference },
                { "22H", Patterns.DoubleSlashSeperator },
                { "22J", Patterns.GetReference },
                { "22K", Patterns.OptionalSingleSlashSeperator },
                { "22X", Patterns.GetReference },
                { "23A", Patterns.SingleSlashSeperator },
                { "23B", Patterns.GetReference },
                { "23C", Patterns.OptionalSingleSlashSeperator },
                { "23D", Patterns.GetReference },
                { "23E", Patterns.OptionalSingleSlashSeperator },
                { "23F", Patterns.OptionalSingleSlashSeperator },
                { "23G", Patterns.OptionalSubFunction },
                { "24B", Patterns.OptionalCode },
                { "24D", Patterns.OptionalSingleSlashSeperator },
                { "25", Patterns.GetReference },
                { "25A", Patterns.OptionalSingleSlashSeperator },
                { "25D", Patterns.OptionalCode },
                { "26E", Patterns.GetReference },
                { "26F", Patterns.GetReference },
                { "26H", Patterns.GetReference },
                { "26N", Patterns.OptionalSingleSlashSeperator },
                { "26P", Patterns.OptionalSingleSlashSeperator },
                { "26T", Patterns.GetReference },
                { "27", Patterns.SingleSlashSeperator },
                { "28", Patterns.OptionalSingleSlashSeperator },
                { "28C", Patterns.OptionalSingleSlashSeperator },
                { "28D", Patterns.SingleSlashSeperator },
                { "28E", Patterns.SingleSlashSeperator },
                { "29A", Patterns.GetAllLines },
                { "29B", Patterns.GetAllLines },
                { "29C", Patterns.GetReference },
                { "29E", Patterns.SingleSlashSeperator },
                { "29F", Patterns.GetAllLines },
                { "29J", Patterns.OptionalSingleSlashSeperator },
                { "29K", Patterns.SingleSlashSeperator },
                { "29H", Patterns.GetReference },
                { "30", Patterns.GetReference },
                { "30F", Patterns.GetReference },
                { "30G", Patterns.SingleSlashSeperator },
                { "30H", Patterns.GetReference },
                { "30P", Patterns.GetReference },
                { "30Q", Patterns.GetReference },
                { "30T", Patterns.GetReference },
                { "30U", Patterns.GetReference },
                { "30V", Patterns.GetReference },
                { "30X", Patterns.GetReference },
                { "31C", Patterns.GetReference },
                { "31E", Patterns.GetReference },
                { "31L", Patterns.GetReference },
                { "31R", Patterns.OptionalSingleSlashSeperator },
                { "31S", Patterns.GetReference },
                { "32A", Patterns.YYMMDDCurrencyAmount },
                { "32B", Patterns.CurrencyAmount },
                { "32C", Patterns.YYMMDDCurrencyAmount },
                { "32D", Patterns.YYMMDDCurrencyAmount },
                { "32E", Patterns.GetReference },
                { "32F", Patterns.NNNValue },
                { "32G", Patterns.CurrencyAmount },
                { "32H", Patterns.SignCurrencyAmount },
                { "32J", Patterns.GetReference },
                { "32M", Patterns.CurrencyAmount },
                { "32P", Patterns.YYMMDDCurrencyAmount },
                { "32Q", Patterns.SingleSlashSeperator },
                { "32U", Patterns.CurrencyAmount },
                { "33A", Patterns.YYMMDDCurrencyAmount },
                { "33B", Patterns.CurrencyAmount },
                { "33C", Patterns.YYMMDDCurrencyAmount },
                { "33D", Patterns.YYMMDDCurrencyAmount },
                { "33E", Patterns.CurrencyAmount },
                { "33F", Patterns.CurrencyAmount },
                { "33P", Patterns.YYMMDDCurrencyAmount },
                { "33R", Patterns.YYMMDDCurrencyAmount },
                { "33S", Patterns.NNNValue },
                { "33T", Patterns.NNNValue },
                { "34A", Patterns.YYMMDDCurrencyAmount },
                { "34B", Patterns.CurrencyAmount },
                { "34F", Patterns.CurrencyAmount },
                { "34P", Patterns.YYMMDDCurrencyAmount },
                { "34R", Patterns.YYMMDDCurrencyAmount },
                { "35", Patterns.GetReference },
                { "35A", Patterns.NNNValue },
                { "35C", Patterns.GetReference },
                { "35D", Patterns.GetReference },
                { "35E", Patterns.GetAllLines },
                { "35F", Patterns.GetAllLines },
                { "35L", Patterns.GetAllLines },
                { "35S", Patterns.NNNValue },
                { "36", Patterns.GetReference },
                { "36A", Patterns.GetReference },
                { "36B", Patterns.DoubleSlashTypeQuantity },
                { "36C", Patterns.DoubleSlashSeperator },
                { "37J", Patterns.GetReference },
                { "37L", Patterns.GetReference },
                { "37N", Patterns.GetAllLines },
                { "37P", Patterns.GetReference },
                { "37U", Patterns.GetReference },
                { "38A", Patterns.GetReference },
                { "38B", Patterns.OptionalCode },
                { "38D", Patterns.GetReference },
                { "38E", Patterns.GetReference },
                { "38G", Patterns.SingleSlashSeperator },
                { "38H", Patterns.SingleSlashSeperator },
                { "39A", Patterns.SingleSlashSeperator },
                { "39B", Patterns.GetReference },
                { "39C", Patterns.GetAllLines },
                { "39P", Patterns.QualifierSlashCurrencyAmount },
                { "40A", Patterns.GetReference },
                { "40B", Patterns.GetAllLines },
                { "40C", Patterns.OptionalSingleSlashSeperator },
                { "40E", Patterns.OptionalSingleSlashSeperator },
                { "40F", Patterns.GetReference },
                { "42C", Patterns.GetAllLines },
                { "42M", Patterns.GetAllLines },
                { "42P", Patterns.GetAllLines },
                { "43P", Patterns.GetReference },
                { "43T", Patterns.GetReference },
                { "44A", Patterns.GetReference },
                { "44B", Patterns.GetReference },
                { "44C", Patterns.GetReference },
                { "44D", Patterns.GetAllLines },
                { "44E", Patterns.GetReference },
                { "44F", Patterns.GetReference },
                { "45A", Patterns.GetAllLines },
                { "45B", Patterns.GetAllLines },
                { "46A", Patterns.GetAllLines },
                { "46B", Patterns.GetAllLines },
                { "47A", Patterns.GetAllLines },
                { "47B", Patterns.GetAllLines },
                { "48", Patterns.GetAllLines },
                { "49", Patterns.GetReference },
                { "50", Patterns.GetAllLines },
                { "50A", Patterns.SlashConditionalLines },
                { "50F", Patterns.SlashConditionalLines },
                { "50G", Patterns.SlashConditionalLines },
                { "50H", Patterns.SlashConditionalLines },
                { "50K", Patterns.SlashConditionalLines },
                { "50L", Patterns.GetReference },
                { "51C", Patterns.PrecedingSlash },
                { "52A", Patterns.SlashConditionalLines },
                { "52C", Patterns.PrecedingSlash },
                { "52D", Patterns.SlashConditionalLines },
                { "52G", Patterns.SlashConditionalLines },
                { "53A", Patterns.SlashConditionalLines },
                { "53B", Patterns.SlashConditionalLines },
                { "53C", Patterns.PrecedingSlash },
                { "53D", Patterns.SlashConditionalLines },
                { "54A", Patterns.SlashConditionalLines },
                { "54B", Patterns.SlashConditionalLines },
                { "54D", Patterns.SlashConditionalLines },
                { "55A", Patterns.SlashConditionalLines },
                { "55D", Patterns.SlashConditionalLines },
                { "56A", Patterns.SlashConditionalLines },
                { "56C", Patterns.PrecedingSlash },
                { "56D", Patterns.SlashConditionalLines },
                { "57A", Patterns.SlashConditionalLines },
                { "57C", Patterns.PrecedingSlash },
                { "57D", Patterns.SlashConditionalLines },
                { "58A", Patterns.SlashConditionalLines },
                { "58C", Patterns.PrecedingSlash },
                { "58D", Patterns.SlashConditionalLines },
                { "59", Patterns.SlashConditionalLines },
                { "59A", Patterns.SlashConditionalLines },
                { "59F", Patterns.SlashConditionalLines },
                { "61", Patterns.DoubleSlashSeperator },
                { "69J", Patterns.DoubleSlashSeperator },
                { "70", Patterns.GetReference },
                { "70C", Patterns.DoubleSlashSeperator },
                { "70E", Patterns.DoubleSlashSeperator },
                { "71A", Patterns.GetReference },
                { "71F", Patterns.CurrencyAmount },
                { "71G", Patterns.CurrencyAmount },
                { "71H", Patterns.CurrencyAmount },
                { "71J", Patterns.CurrencyAmount },
                { "71K", Patterns.CurrencyAmount },
                { "71L", Patterns.CurrencyAmount },
                { "73", Patterns.GetAllLines },
                { "74", Patterns.GetAllLines },
                { "75", Patterns.GetAllLines },
                { "76", Patterns.GetAllLines },
                { "80C", Patterns.GetAllLines },
                { "82A", Patterns.SlashConditionalLines },
                { "82B", Patterns.SlashConditionalLines },
                { "82D", Patterns.SlashConditionalLines },
                { "83A", Patterns.SlashConditionalLines },
                { "83C", Patterns.PrecedingSlash },
                { "83D", Patterns.SlashConditionalLines },
                { "84A", Patterns.SlashConditionalLines },
                { "84D", Patterns.SlashConditionalLines },
                { "86", Patterns.SlashConditionalLines },
                { "90A", Patterns.DoubleSlashTypeQuantity },
                { "90B", Patterns.AmountTypeCurrencyValue },
                { "90E", Patterns.DoubleSlashSeperator },
                { "92A", Patterns.DoubleSlashSeperator },
                { "92C", Patterns.OptionalCode },
                { "92K", Patterns.DoubleSlashSeperator },
                { "93A", Patterns.OptionalCode },
                { "94A", Patterns.GetReference },
                { "94B", Patterns.OptionalCodeWithOptionalNarrative },
                { "94C", Patterns.DoubleSlashSeperator },
                { "94D", Patterns.OptionalCode },
                { "94F", Patterns.OptionalCode },
                { "95C", Patterns.DoubleSlashSeperator },
                { "95P", Patterns.DoubleSlashSeperator },
                { "95Q", Patterns.DoubleSlashSeperator },
                { "95R", Patterns.CodeWithNarrative },
                { "97A", Patterns.DoubleSlashSeperator },
                { "97B", Patterns.OptionalCodeWithOptionalNarrative },
                { "97C", Patterns.DoubleSlashSeperator },
                { "98A", Patterns.DoubleSlashSeperator },
                { "98B", Patterns.OptionalCode },
                { "98C", Patterns.DoubleSlashSeperator },
                { "99A", Patterns.DoubleSlashSeperator },
                { "99B", Patterns.DoubleSlashSeperator }
            };
    }
}
